name: flutter_ui_screens
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.3
  audioplayers: ^0.20.1
  flame: ^1.7.0
  flame_forge2d: ^0.13.0
  scidart: ^0.0.2-dev.12
  dart_numerics: ^0.0.6
  rxdart: ^0.27.7
  vector_math: ^2.1.4
  particle_field: ^1.0.0
  rnd: ^0.2.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  phosphor_flutter: ^2.0.0
  carousel_slider: ^4.2.1
  shared_preferences: ^2.1.0
  image_sequence_animator: ^2.0.0
  sensors_plus: ^3.0.0
  flutter_riverpod: ^2.3.6
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/car/
  generate: true
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Crawl
      fonts:
        - asset: assets/fonts/crawl_regular.ttf

